// Generated by scripts/build-service-worker.js — do not edit by hand
const CACHE_VERSION = 'mmq7g2nq';
const CACHE_NAME = 'crimson-lane-v' + CACHE_VERSION;

const FILES_TO_CACHE = [
  './css/hero-viewer.css',
  './index.html',
  './js/ai.js',
  './js/animations.js',
  './js/audio.js',
  './js/combat.js',
  './js/constants.js',
  './js/controls.js',
  './js/creeps.js',
  './js/hero-models.js',
  './js/hero-viewer.js',
  './js/heroes.js',
  './js/heroes/_template.js',
  './js/heroes/axe.js',
  './js/heroes/bounty_hunter.js',
  './js/heroes/crystal_maiden.js',
  './js/heroes/dragon_knight.js',
  './js/heroes/drow_ranger.js',
  './js/heroes/earthshaker.js',
  './js/heroes/enigma.js',
  './js/heroes/juggernaut.js',
  './js/heroes/lich.js',
  './js/heroes/lina.js',
  './js/heroes/lion.js',
  './js/heroes/phantom_assassin.js',
  './js/heroes/pudge.js',
  './js/heroes/registry.js',
  './js/heroes/shadow_fiend.js',
  './js/heroes/sniper.js',
  './js/heroes/sven.js',
  './js/heroes/tidehunter.js',
  './js/heroes/vengeful_spirit.js',
  './js/heroes/windrunner.js',
  './js/heroes/zeus.js',
  './js/hud.js',
  './js/i18n.js',
  './js/items.js',
  './js/main.js',
  './js/map.js',
  './js/net/client.js',
  './js/net/host.js',
  './js/net/lobby.js',
  './js/net/peer.js',
  './js/net/protocol.js',
  './js/particles.js',
  './js/scene.js',
  './js/skills.js',
  './js/state.js',
  './js/towers.js',
  './locales/en.json',
  './locales/vi.json',
  './manifest.json',
  './sounds/assassinate_channel.wav',
  './sounds/assassinate_fire.wav',
  './sounds/buy.wav',
  './sounds/chain_frost.wav',
  './sounds/death.wav',
  './sounds/fire.wav',
  './sounds/frost.wav',
  './sounds/gold.wav',
  './sounds/hit.wav',
  './sounds/levelup.wav',
  './sounds/magic.wav',
  './sounds/ranged_hit.wav',
  './sounds/respawn.wav',
  './sounds/shrapnel.wav',
  './sounds/spawn.wav',
  './sounds/tower_death.wav',
  './sounds/tower_hit.wav',
  './sounds/windrun.wav'
];

self.addEventListener('install', (ev) => {
  ev.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(FILES_TO_CACHE))
      .then(() => self.skipWaiting())
      .catch((err) => console.warn('SW install cache addAll failed:', err))
  );
});

self.addEventListener('activate', (ev) => {
  ev.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k.startsWith('crimson-lane-') && k !== CACHE_NAME).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (ev) => {
  if (ev.request.method !== 'GET') return;
  ev.respondWith(
    caches.match(ev.request).then((cached) => cached || fetch(ev.request))
  );
});
